name: Update Theme

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日的午夜运行
  workflow_dispatch: # 手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Update theme submodule
        run: |
          git submodule update --remote --merge
          git config --global user.email "1032615837@qq.com"
          git config --global user.name "nikoioi"
          git add .
          git commit -m "chore: update theme submodule"
          git push origin main
