name: Update Theme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天自动更新

jobs:
  update-theme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          
      - name: Configure git
        run: |
          git config --global user.name "alllynnn"
          git config --global user.email "${{ secrets.USER_EMAIL }}"
          
      - name: Update theme
        run: |
          cd themes/anzhiyu
          git pull origin main
          cd ../..
          
      - name: Commit and push
        run: |
          git add .
          git commit -m "chore: update theme" || echo "No changes to commit"
          git push
